# =========================================================
# Browser and execution configuration
# =========================================================

execution.mode=LOCAL
browser=CHROME
headless=true

# =========================================================
# Application configuration
# =========================================================

application.url=https://demowebshop.tricentis.com/login

# =========================================================
# Application configuration
# =========================================================

login.valid.email=vivek.ranjan.srm@gmail.com
login.valid.password=demowebshop
login.invalid.password=demowebshop123

# =========================================================
# Browser certificate configuration
# =========================================================

accept.insecure.certificates=false

# =========================================================
# Download configuration
# =========================================================

downloads.enabled=false
download.directory=target/downloads

# =========================================================
# Test execution configuration
# =========================================================

run.only.merged.tests=OFF

# =========================================================
# Jira configuration
# =========================================================

jira.enabled=OFF

# =========================================================
# Docker Selenium Grid configuration
# =========================================================

# Enable these when Docker execution is required
# execution.mode=DOCKER
# docker.hub.url=http://localhost:4444

# =========================================================
# LambdaTest cloud execution
# =========================================================

# Enable these when LambdaTest execution is required
# execution.mode=LAMBDATEST
# lambdatest.url=https://username:accesskey@hub.lambdatest.com/wd/hub